insert into public.notification_templates (tenant_id,event_type,channel,name,subject_template,body_template,active)
select null,'support_ticket_customer_confirmation','email','Support ticket customer confirmation',
'Support request {{ticket_number}} received',
'<h2 style="margin:0 0 16px;color:#24467f">We received your support request</h2><p>Your request has been added to the screenings4u Support queue.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:18px 0;border-collapse:collapse"><tr><td style="padding:10px 12px;background:#f2f6fc;border:1px solid #dfe6f0"><strong>Ticket</strong></td><td style="padding:10px 12px;border:1px solid #dfe6f0">{{ticket_number}}</td></tr><tr><td style="padding:10px 12px;background:#f2f6fc;border:1px solid #dfe6f0"><strong>Subject</strong></td><td style="padding:10px 12px;border:1px solid #dfe6f0">{{subject}}</td></tr><tr><td style="padding:10px 12px;background:#f2f6fc;border:1px solid #dfe6f0"><strong>Priority</strong></td><td style="padding:10px 12px;border:1px solid #dfe6f0">{{priority}}</td></tr></table><p>You can track this request from the Support page in your portal. Reply to this message if you need to add information.</p><p style="color:#66758a;font-size:13px">Page reported: {{page_url}}</p>',true
where not exists (select 1 from public.notification_templates where tenant_id is null and event_type='support_ticket_customer_confirmation' and channel='email');

insert into public.notification_templates (tenant_id,event_type,channel,name,subject_template,body_template,active)
select null,'support_ticket_admin_created','email','Support ticket admin notification',
'New support request {{ticket_number}} — {{organization_name}}',
'<h2 style="margin:0 0 16px;color:#24467f">New Support Request</h2><p>A customer support ticket was created and is available in the backend Support queue.</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:18px 0;border-collapse:collapse"><tr><td style="padding:9px 11px;background:#f2f6fc;border:1px solid #dfe6f0"><strong>Ticket</strong></td><td style="padding:9px 11px;border:1px solid #dfe6f0">{{ticket_number}}</td></tr><tr><td style="padding:9px 11px;background:#f2f6fc;border:1px solid #dfe6f0"><strong>Customer</strong></td><td style="padding:9px 11px;border:1px solid #dfe6f0">{{organization_name}} — {{customer_email}}</td></tr><tr><td style="padding:9px 11px;background:#f2f6fc;border:1px solid #dfe6f0"><strong>Portal</strong></td><td style="padding:9px 11px;border:1px solid #dfe6f0">{{portal}}</td></tr><tr><td style="padding:9px 11px;background:#f2f6fc;border:1px solid #dfe6f0"><strong>Subject</strong></td><td style="padding:9px 11px;border:1px solid #dfe6f0">{{subject}}</td></tr><tr><td style="padding:9px 11px;background:#f2f6fc;border:1px solid #dfe6f0"><strong>Priority</strong></td><td style="padding:9px 11px;border:1px solid #dfe6f0">{{priority}}</td></tr></table><p><strong>Description</strong></p><p>{{message}}</p><p><strong>Page URL</strong><br>{{page_url}}</p><p><strong>Detected page error</strong></p><pre style="white-space:pre-wrap;background:#f2f6fc;border:1px solid #dfe6f0;padding:12px;border-radius:8px">{{detected_error}}</pre><p><strong>Console / F12 message</strong></p><pre style="white-space:pre-wrap;background:#f2f6fc;border:1px solid #dfe6f0;padding:12px;border-radius:8px">{{console_error}}</pre>',true
where not exists (select 1 from public.notification_templates where tenant_id is null and event_type='support_ticket_admin_created' and channel='email');
